pub const GRID_SIZE_X: u32 = 24;
pub const GRID_SIZE_Y: u32 = 32;
pub const PLAYER_SCALE: f32 = 4.0; // Scale for rendering
pub const PLAYER_Z: f32 = 2.0; // Z position for rendering
pub const PLAYER_MAX_SPEED: f32 = 800.0; // Max speed for player movement
pub const TILE_SIZE: i32 = 16;
pub const TILE_SCALE: f32 = 3.0; // Scale for rendering
pub const MAP_WIDTH: i32 = 54; // For a larger farm
pub const MAP_HEIGHT: i32 = 36;
